---
title: "Data Cleaning"
author: "Jenna Honan"
date: "9/1/2022"
edited: "5/2/2023"
output: html_document
---

#Data Cleaning

Note: This is the first Rmd code to be run prior to the data analysis.

```{r settingup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## Required libraries
library(readxl)
library(writexl)
library(dplyr)
library(fastDummies)
library(ggforce)

#Setting WD
#setwd("~/Desktop/Research Projects/Yuma/Yuma_Perchlorate/")

## Importing Data
Metals <- read_excel("Yuma_HQ_DataFile.xlsx", sheet = "Original_Uneditted") #This dataset includes demographic information for Yuma study

#Notes: Difference Between Metals and Metalloids
  #Metals have unique metallic properties such as shiny appearance, high density, higher melting points and electric conductivity. 
  #However, metalloids possess both metal properties and non-metal properties. 
  #Metals are located in the left side of the periodic table while metalloids are in the middle of metals and non-metals.

Creatinine <- read_excel("2021-0072_Urinary Creatinine Results.xlsx", skip=6)
Perchlorate <- read_excel("2021-0072_Urinary Perchlorate Report.xlsx", skip=7)

#For this study, we included people who had either SR or EMR data regarding thyroid diagnoses and completed a demographic questionnaire. TOTAL N WILL REFLECT THIS NUMBER.
```

## Data Cleaning
```{r dataclean}
#Metals Data / Demographic Data
#Reformating Date Data
Metals$Date <- as.Date(as.numeric(Metals$Date), origin = "1899-12-30")
Metals$DOB <- as.Date(as.numeric(Metals$DOB), origin = "1899-12-30")

### Fixing birthdays that were not correctly read by xl based on feedback from Mark Remiker, December 2022 ###
#Note: C1045 is obviously an error on the part of the survey administrator.
Metals$DOB_year <- ifelse(!is.na(Metals$DOB_year), Metals$DOB_year+1900, Metals$DOB_year)

#Using 'Perchlorate codebook.pdf' as data dictionary

### Additional Notes from Mark Remiker, August 2022 ###
#Num_in_household -	No data entry error here - that’s the response!  
#Num_children -	Same!  That’s the actual response.  
#Armed_forces -	1 = Yes, 2 = No, 3 = Don’t know, 4 = Refuse, 61 = Yes, 62 = No, 63 = Don’t know, 64 = Refuse
Metals$Armed_forces[Metals$Armed_forces==62] <- 2
#Employment -	1 = Working for pay, 2= Self-employed, 3= Looking for work, 4= Temporarily laid off, 5 = Retired, 6= A homemaker, 7= Student, 8= Permanently disabled, 9= Maternity/sick leave, 10= Other, 11= Don’t know, 12 = Refused
#Health_care -	21= Yes, 22= No, 24= I don’t know, 23= Refuse
Metals$Health_care[Metals$Health_care==21] <- 1
Metals$Health_care[Metals$Health_care==22] <- 2
#Health_consult -	21= Yes, 22= No, 24= I don’t know, 23= Refuse
Metals$Health_consult[Metals$Health_consult==31] <- 1
Metals$Health_consult[Metals$Health_consult==32] <- 2
Metals$Health_consult[Metals$Health_consult==33] <- 3
Metals$Health_consult[Metals$Health_consult==34] <- 4
Metals$Health_consult[Metals$Health_consult==35] <- 5


#Generally "." is missing data
Metals2 <- subset(Metals, select=-c(Date, DOB))

Metals2[Metals2=="."] <- NA

Metals3 <- subset(Metals, select=c(Date, DOB))

Metals <- cbind(Metals2, Metals3)

remove(Metals2)
remove(Metals3)
#Participant C1045 was 9/4/2018. This is obviously a mistake. Need to ask Mark to see if he can find the correct birthdate elsewhere.
#This person did not have an EMR, and CSF is not able to verify birthday.

Metals$Date[Metals$Date=="2013-01-04"] <- "2018-09-04"

#Metals <- Metals %>%
#  filter(!is.na(DOB_year))

#Perchlorate and Creatinine Data
Creatinine$`Sample ID` <- gsub("YRMC-", "Y1", Creatinine$`Sample ID`)
Perchlorate$`Sample ID` <- gsub("YRMC-", "Y1", Perchlorate$`Sample ID`)

Urine_Perch_Creat <- merge(Creatinine, Perchlorate, by=c("Sample ID"), all = T)

Urine_Perch_Creat <- as.data.frame(Urine_Perch_Creat)
Urine_Perch_Creat <- Urine_Perch_Creat[, c("Sample ID", "Result.x", "LOD.x", "Result.y", "LOD.y")]
unique(Creatinine$Units)
unique(Perchlorate$Units)
colnames(Urine_Perch_Creat) <- c("Sample_ID", "Result_C_mg_dL", "LOD_C", "Result_P_ng_mL", "LOD_P")

Urine_Perch_Creat$Result_C[Urine_Perch_Creat$Result_C=="NR"] <- NA

Urine_Perch_Creat$Site <- substr(as.character(Urine_Perch_Creat$Sample_ID),7,7)
Urine_Perch_Creat$ID <- substr(as.character(Urine_Perch_Creat$Sample_ID),7,11)

#Of the 297 observations, 2 have missing values for both creatinine and perchlorate, and 1 has missing value for creatinine but measured values for perchlorate, such that 294 observations are paired with measured values.

#I will remove the folks that don't have any data for creatinine or perchlorate since they aren't particularly helpful
Urine_Perch_Creat <- Urine_Perch_Creat %>% 
  filter(!(is.na(Result_C) & is.na(Result_P_ng_mL)))

Urine_Perch_Creat %>% 
  filter(!is.na(Result_P_ng_mL)) %>% 
  summarize("Number Part. with Perchlorate"=length(unique(Sample_ID)))

Urine_Perch_Creat %>% 
  filter(!is.na(Result_C_mg_dL)) %>% 
  summarize("Number Part. with Creatinine"=length(unique(Sample_ID)))
```

## Wondering About Recodes
```{r recoded}
Metals[grepl('recode', colnames(Metals))]

#It looks like Jonathan Credo (who did the recodes?) maybe tried to create dummy variables from the categorical variables?
#Unfortunately they are not adding up very well (and lots of NAs).

#There are also thyroid variables with the suffix _D that look like they are dummy variables.
Metals[grepl('_D', colnames(Metals))]
#These ones include "don't know" and "prefer not to answer" in the "No" category.
```


```{r combined}
#Combining Metal and Perchlorate Data for single dataframe
All_Data <- merge(Metals, Urine_Perch_Creat, by = "ID", all = TRUE)

#Testing_Data_Clean <- write_xlsx(All_Data, "TEST_All_Data.xlsx")
#Testing_Data_Clean <- All_Data

#All_Data <- All_Data %>% 
#  filter(!is.na(DOB_year))
#Age/DOB information is not provided for the following participants: C1050, C1059, R1048, R1083. These participants do not have any associated survey data. Same for C1104, Y1008, and Y1015.

#test <- All_Data[,c("ID", "Mn55",  "Cu65", "Cd111", "Hg202", "Pb206", "Pb207", "Pb208", "U238", "Result_C_mg_dL", "Result_P_ng_mL")]
#sum(is.na(test$Mn55) & is.na(test$Cu65) & is.na(test$Cd111) & is.na(test$Hg202) & is.na(test$Pb206) & is.na(test$Pb207) & is.na(test$Pb208) & is.na(test$U238) & is.na(test$Result_C_mg_dL) & is.na(test$Result_P_ng_mL))

#test <- All_Data[,c("ID","Mn55",  "Cu65", "Cd111", "Hg202", "Pb206", "Pb207", "Pb208", "U238", "Result_C_mg_dL", "Result_P_ng_mL", "thyroid_prob", "hypothyroid", "emr_thyroid_problem", "emr_hypothyroidism")]
#sum(is.na(test$Mn55) & is.na(test$Cu65) & is.na(test$Cd111) & is.na(test$Hg202) & is.na(test$Pb206) & is.na(test$Pb207) & is.na(test$Pb208) & is.na(test$U238) & is.na(test$Result_C_mg_dL) & is.na(test$Result_P_ng_mL) & is.na(test$thyroid_prob) & is.na(test$hypothyroid) & is.na(test$emr_thyroid_problem) & is.na(test$emr_hypothyroidism))
#There are 26 people who do not have any data for hair metals nor perchlorate information.
#There are 2 people who do not have metal, perchlorate, or thyroid information.

#Fixing column names and missing site data
All_Data$Site.x[All_Data$ID == 'C1050'] <- 1
All_Data$Site.x[All_Data$ID == 'C1059'] <- 1
All_Data$Site.x[All_Data$ID == 'R1048'] <- 2
All_Data$Site.x[All_Data$ID == 'R1083'] <- 2

colnames(All_Data)[which(names(All_Data) == "Site.x")] <- "Site"
All_Data <- subset (All_Data, select = -Site.y)
```

```{r emr_fixins}
All_Data$emr_thyroid_problem_fromothercolumns <- ifelse(All_Data$emr_thyroid_cancer==1|
                                                          All_Data$emr_hyperthyroidism==1|
                                                          All_Data$emr_hypothyroidism==1|
                                                          All_Data$emr_goiter==1|
                                                          All_Data$emr_thyroid_problem==1, 1,
                                                        ifelse(All_Data$emr_thyroid_cancer==0&
                                                          All_Data$emr_hyperthyroidism==0&
                                                          All_Data$emr_hypothyroidism==0&
                                                          All_Data$emr_goiter==0&
                                                          All_Data$emr_thyroid_problem==0,0,
                                                          NA))
```

```{r self_report_fixins}
#1=Yes
#2=No
#3=Don't know
#4=Refused
#NA=Missing

#The original coding for this variable looks like it includes "Don't know" and "Refused" options as "No" responses. I do not believe this should be the case, since these responses don't actually give us any information about the presence or absence of the diseases. So I am going to update these values here. There were 320 people who responded to these questions.


All_Data$thyroid_prob_D <- ifelse(All_Data$thyroid_prob==1, 1,
                                  ifelse(All_Data$thyroid_prob==2, 0,
                                         NA))

All_Data$Hyper_D <- ifelse(All_Data$hyperthyroid==1, 1,
                           ifelse(All_Data$hyperthyroid==2, 0,
                                  NA))

All_Data$Hypo_D <- ifelse(All_Data$hypothyroid==1, 1,
                          ifelse(All_Data$hypothyroid==2, 0,
                                 NA))

All_Data$Thyroid_cancer_D <- ifelse(All_Data$thyroid_cancer==1, 1,
                                    ifelse(All_Data$thyroid_cancer==2, 0,
                                           NA))

All_Data$Goiter_D <- ifelse(All_Data$goiter==1, 1,
                            ifelse(All_Data$goiter==2, 0,
                                   NA))

All_Data$any_thyroid_problem_dummy <- ifelse(All_Data$thyroid_prob_D==1 | 
                                               All_Data$Hyper_D==1 | 
                                               All_Data$Hypo_D==1 | 
                                               All_Data$Thyroid_cancer_D==1 | 
                                               All_Data$Goiter_D==1, 1,
                                                        ifelse(All_Data$thyroid_prob_D==0 &
                                                                 All_Data$Hyper_D==0 & 
                                                                 All_Data$Hypo_D==0 & 
                                                                 All_Data$Thyroid_cancer_D==0 & 
                                                                 All_Data$Goiter_D==0, 0,
                                                               NA))

All_Data$SR_hypo_goit_canc <- ifelse(All_Data$Hypo_D==1 |
                                       All_Data$Thyroid_cancer_D==1 |
                                       All_Data$Goiter_D==1, 1,
                                     ifelse(All_Data$Hypo_D==0 &
                                              All_Data$Thyroid_cancer_D==0 &
                                              All_Data$Goiter_D==0, 0,
                                            NA))

All_Data %>% 
  summarise(n=sum(SR_hypo_goit_canc==1, na.rm = T),
            m=sum(SR_hypo_goit_canc==0, na.rm = T),
            hypo=sum(hypothyroid==1, na.rm = T),
            canc=sum(thyroid_cancer==1, na.rm = T),
            goiter=sum(goiter==1, na.rm = T),
            hypoandgoit=sum(hypothyroid==1&goiter==1, na.rm = T),
            hypoandcanc=sum(hypothyroid==1&thyroid_cancer==1, na.rm = T))


All_Data$EMR_hypo_goit_canc <- ifelse(All_Data$emr_hypothyroidism==1 |
                                       All_Data$emr_thyroid_cancer==1 |
                                       All_Data$emr_goiter==1, 1,
                                     ifelse(All_Data$emr_hypothyroidism==0 &
                                              All_Data$emr_thyroid_cancer==0 &
                                              All_Data$emr_goiter==0, 0,
                                            NA))

All_Data %>% 
  summarise(n=sum(EMR_hypo_goit_canc==1, na.rm = T),
            m=sum(EMR_hypo_goit_canc==0, na.rm = T),
            hypo=sum(emr_hypothyroidism==1, na.rm = T),
            canc=sum(emr_thyroid_cancer==1, na.rm = T),
            goiter=sum(emr_goiter==1, na.rm = T),
            hypoandgoit=sum(emr_hypothyroidism==1&emr_goiter==1, na.rm = T),
            hypoandcanc=sum(emr_hypothyroidism==1&emr_thyroid_cancer==1, na.rm = T))

All_Data$EMR_any_thyroid_Dummy <- ifelse(All_Data$emr_hypothyroidism==1 |
                                           All_Data$emr_hyperthyroidism==1|
                                           All_Data$emr_thyroid_cancer==1 |
                                           All_Data$emr_goiter==1 |
                                           All_Data$emr_thyroid_problem==1,  1,
                                     ifelse(All_Data$emr_hypothyroidism==0 &
                                              All_Data$emr_hyperthyroidism==0 &
                                              All_Data$emr_thyroid_cancer==0 &
                                              All_Data$emr_goiter==0 &
                                              All_Data$emr_thyroid_problem==0, 0,
                                            NA))

#All_Data$any_thyroid_Dummy_EMR_or_SR <- ifelse(All_Data$emr_hypothyroidism==1 |
#                                                 All_Data$emr_hyperthyroidism==1|
#                                                 All_Data$emr_thyroid_cancer==1 |
#                                                 All_Data$emr_goiter==1 |
#                                                 All_Data$emr_thyroid_problem==1 |
#                                                 All_Data$thyroid_prob_D==1 |
#                                                 All_Data$Hyper_D==1 | 
#                                                 All_Data$Hypo_D==1 | 
#                                                 All_Data$Thyroid_cancer_D==1 | 
#                                                 All_Data$Goiter_D==1,  1,
#                                     ifelse(All_Data$emr_hypothyroidism==0 &
#                                              All_Data$emr_hyperthyroidism==0 &
#                                              All_Data$emr_thyroid_cancer==0 &
#                                              All_Data$emr_goiter==0 &
#                                              All_Data$emr_thyroid_problem==0 &
#                                              All_Data$thyroid_prob_D==0 &
#                                              All_Data$Hyper_D==0 & 
#                                              All_Data$Hypo_D==0 & 
#                                              All_Data$Thyroid_cancer_D==0 & 
#                                              All_Data$Goiter_D==0, 0,
#                                            NA))

#All_Data$any_thyroid_Dummy_EMR_or_SR <- ifelse(All_Data$any_thyroid_problem_dummy == 1 |
#                                               All_Data$EMR_any_thyroid_Dummy == 1, 1,
#                                               ifelse(All_Data$any_thyroid_problem_dummy == 0 &
#                                                      All_Data$EMR_any_thyroid_Dummy == 0, 0,
#                                                      ifelse(All_Data$any_thyroid_problem_dummy == 0 & is.na(All_Data$EMR_any_thyroid_Dummy), 0, ifelse(is.na(All_Data$any_thyroid_problem_dummy) & is.na(All_Data$EMR_any_thyroid_Dummy), NA, NA))))

#All_Data$any_thyroid_Dummy_EMR_or_SR <- ifelse(All_Data$any_thyroid_problem_dummy == 1 |
#                                               All_Data$EMR_any_thyroid_Dummy == 1, 1,
#                                               ifelse(All_Data$any_thyroid_problem_dummy == 0 &
#                                                      All_Data$EMR_any_thyroid_Dummy %in% c(0, NA), 0,
#                                                      NA))

#I don't know why the above aren't working, but let's try a different approach
All_Data <- All_Data %>%
  mutate(any_thyroid_Dummy_EMR_or_SR = case_when(
    any_thyroid_problem_dummy == 1 | EMR_any_thyroid_Dummy == 1 ~ 1,
    any_thyroid_problem_dummy == 0 & EMR_any_thyroid_Dummy == 0 ~ 0,
    any_thyroid_problem_dummy == 0 & is.na(EMR_any_thyroid_Dummy) ~ 0,
    is.na(any_thyroid_problem_dummy) & is.na(EMR_any_thyroid_Dummy) ~ NA_real_, TRUE ~ NA_real_)) #Cool, this worked better.

sum(All_Data$any_thyroid_problem_dummy==1, na.rm = T) #145, does not match Bob's paper that says 147.
sum(All_Data$any_thyroid_problem_dummy==0, na.rm = T) #172
sum(is.na(All_Data$any_thyroid_problem_dummy)) #13 - These people need to be excluded

sum(All_Data$EMR_any_thyroid_Dummy==1, na.rm = T) #138
sum(All_Data$EMR_any_thyroid_Dummy==0, na.rm = T) #114
sum(is.na(All_Data$EMR_any_thyroid_Dummy)) #78

sum(All_Data$any_thyroid_Dummy_EMR_or_SR==1, na.rm = T) #157
sum(All_Data$any_thyroid_Dummy_EMR_or_SR==0, na.rm = T) #161
sum(is.na(All_Data$any_thyroid_Dummy_EMR_or_SR)) #12



```

```{r demographic_numbers}
All_Data$Below_Pov <- ifelse(All_Data$Num_in_household==1 & All_Data$Income<=3, 1, 
                             ifelse(All_Data$Num_in_household==2 & All_Data$Income<=4, 1,
                                    ifelse(All_Data$Num_in_household==3 & All_Data$Income<=5, 1,
                                           ifelse(All_Data$Num_in_household==4 & All_Data$Income<=5, 1,
                                                  ifelse(All_Data$Num_in_household==5 & All_Data$Income<=5, 1,
                                                         ifelse(All_Data$Num_in_household==6 & All_Data$Income<=6, 1,
                                                                ifelse(All_Data$Num_in_household==7 & All_Data$Income<=6, 1,
                                                                       ifelse(All_Data$Num_in_household>=8 & All_Data$Income<=7, 1,
                                                                              ifelse(is.na(All_Data$Income), NA, 0)))))))))


All_Data$Race <- ifelse(!is.na(All_Data$Race_ai_an==1), 1, 
                        ifelse(!is.na(All_Data$Race_asian==1), 2, 
                               ifelse(!is.na(All_Data$Race_black==1), 3, 
                                      ifelse(!is.na(All_Data$Race_pac_isl==1), 4, 
                                             ifelse(!is.na(All_Data$Race_white==1), 5,
                                                    ifelse(!is.na(All_Data$Race_other==1), 6,
                                                           ifelse(!is.na(All_Data$Race_dk==1), 7,
                                                                  ifelse(!is.na(All_Data$Race_refuse==1), 8, NA))))))))
#If more than one is selected
which(colnames(All_Data)=="Race_ai_an") #16
which(colnames(All_Data)=="Race_refuse") #23

columns_to_convert <- c("Race_ai_an", "Race_asian", "Race_black", 
                         "Race_pac_isl", "Race_white", "Race_other",
                         "Race_dk", "Race_refuse")

All_Data[columns_to_convert] <- lapply(All_Data[columns_to_convert], as.numeric)

All_Data$Race <- ifelse(!is.na(All_Data$Race_ai_an==1), 1, 
                        ifelse(!is.na(All_Data$Race_asian==1), 2, 
                               ifelse(!is.na(All_Data$Race_black==1), 3, 
                                      ifelse(!is.na(All_Data$Race_pac_isl==1), 4, 
                                             ifelse(!is.na(All_Data$Race_white==1), 5,
                                                    ifelse(!is.na(All_Data$Race_other==1), 6,
                                                           ifelse(!is.na(All_Data$Race_dk==1), 7,
                                                                  ifelse(!is.na(All_Data$Race_refuse==1), 8,
                                                                         ifelse(rowSums(All_Data[,8:15])>1, 9, NA)))))))))


All_Data$thyroid_med[is.na(All_Data$thyroid_med)] <- 0 #assuming that anyone who doesn't have meds listed is not taking them.
All_Data$tsh_med[is.na(All_Data$tsh_med)] <- 0
All_Data$free_t4_med[is.na(All_Data$free_t4_med)] <- 0
All_Data$free_t3_med[is.na(All_Data$free_t3_med)] <- 0
All_Data$total_t4_med[is.na(All_Data$total_t4_med)] <- 0
All_Data$total_t3_med[is.na(All_Data$total_t3_med)] <- 0

#Creating a column that combines the different drinking water sources for home/cooking/coffee/work.
#Water 1: City
#Water 2: Well
#Water 3: Bottled
#Water 4: Other

#New column: 
#Water 1: City
#Water 2: Well
#Water 3: Bottled
#Water 4: Other
#Water 5: Mixed Sources

All_Data$Water_all <- ifelse(All_Data$Water_coffee==All_Data$Water_cooking & All_Data$Water_coffee==All_Data$Water_home & All_Data$Water_coffee==All_Data$Water_work, All_Data$Water_coffee,
                             ifelse(All_Data$Water_coffee!=All_Data$Water_cooking | All_Data$Water_coffee!=All_Data$Water_home | All_Data$Water_coffee!=All_Data$Water_work, 5, NA))
```